spring:
  datasource:
    url: jdbc:mysql://localhost:3306/intly_api
    username: youn
    password: youn
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: false
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        format_sql: true

security:
  jwt:
    secret-key: intly
    expiration: 3600000